/**
 * Auto-generated type definitions from JSON configuration files
 * Generated from: /Users/walid/Development/Nextnode/nextnode-front/config
 * DO NOT EDIT MANUALLY - This file is automatically generated
 */

declare module '@nextnode/config-manager' {
	interface UserConfigSchema {
		readonly app: {
			readonly name: string
			readonly version: string
			readonly features: readonly string[]
			readonly environment: string
		}
		readonly email: {
			readonly provider: string
			readonly from: string
			readonly to: string
			readonly replyTo: string
			readonly templates: {
				readonly projectRequest: {
					readonly subject: string
					readonly companyName: string
					readonly websiteUrl: string
					readonly companyLogo: null
				}
			}
		}
	}
}

export {}
